# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You can change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

# To connect, go to https://play.dgraph.io/?latest# and add the connection 
# http://localhost:8080

version: "3.2"
services:

  zero:
    image: dgraph/dgraph:latest
    # volumes:
    #   - ./dgraph/zero:/dgraph
    ports:
      - "5080:5080"
      - "6080:6080"
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha1:
    image: dgraph/dgraph:latest
    # volumes:
    #   - ./dgraph/alpha1:/dgraph
    ports:
      - "7080:7080"
      - "8080:8080"
      - "9080:9080"
    restart: on-failure
    command: dgraph alpha --my=alpha1:7080 --zero=zero:5080 --security "whitelist=0.0.0.0/0"

  alpha2:
    image: dgraph/dgraph:latest
    # volumes:
    #   - ./dgraph/alpha2:/dgraph
    ports:
      - "7081:7081"
      - "8081:8081"
      - "9081:9081"
    restart: on-failure
    command: dgraph alpha --my=alpha2:7081 --zero=zero:5080 -o=1 --security "whitelist=0.0.0.0/0"
